# Generated by Django 2.0.4 on 2018-04-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('customer', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='proj_images')),
                ('descripion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='tech_images')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
    ]
