# Generated by Django 2.0.4 on 2018-04-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amstudio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripion',
            new_name='description',
        ),
    ]
